const code = [
  "What Is 'State' in ReactJS?",
  "What are the various Data Types of JS?",
  "What is difference between for-loop and forEach() ?",
  "What is the difference between let and var?",
  "How do you check if it is array or not?",
  "What is closure in JavaScript?",
  "What is Semantics tag?",
  "What is SEO?",
  "What is Reference types",
  "What is Version Control?",
  "What is Difference between div and span?",
  "Mention three ways to decrease page load time?",
  "What is attribute?",
  "What is React JS?",
  "What is Bubbling and Capturing Event?",
  "How browsers render the UI?",
  "What is prototype?",
  "What is AJAX",
  "What is a callback function?",
  "What is a promise?",
  "Difference between undefined and null",
  "Primitive Type and Non-Primitive Type",
  "Shallow Copy and Deep Copy",
  "What is DOM?",
  "Static Sites, CSR, SSR",
  "What is REST API?",
  "What is Node.js?",
  "What is Cross-browser compatibility?",
  "What are Asynchronous and Synchronous",
  "What is the keyword `this`?",
  "What is CRUD?",
  "Can you explain how you would optimize the load time of a web page?",
  "How do you approach accessibility when building a website?",
  "How do you use version control systems, such as Git, in your workflow?",
  "Can you describe a project you have worked on that required you to use responsive design?",
  "How do you approach security when building web application?",
  "What is IIFE?",
  "What is ES6?",
  "Destructuring Assignment",
  "What is OOP?",
  "What is Call Stack?",
];

const word = [
  "Declare",
  "Potential",
  "Exhibit",
  "Compressing",
  "Utilize",
  "Accumulate",
  "Perform",
  "Complexity",
  "Maintained",
  "Inheritance",
  "Reusability",
  "Lacking",
  "Numerous",
  "Contrary",
  "Harm",
  "Manipulate",
  "Modify",
  "Essential",
  "Compatibility",
  "Ponder",
  "Access",
  "Properly",
  "Participant",
  "Invoked",
  "Coverage",
  "Extensive",
  "Minify",
  "Discrepancies",
  "Enhanced",
  "Vital",
  "Disregard",
  "Regarded",
  "mutable / imutable",
];

const personal = [
  "Tell me about yourself.",
  "Why are you interested in working for this company?",
  "Tell me about your education.",
  "Why have you chosen this particular field?",
  "Describe your best/worst boss.",
  "In a job, what interests you most/least?",
  "Give an example of how you solved a problem in the past.",
  "How do others describe you?",
  "What do you consider your best accomplishment in your last job?",
  "Where do you see yourself in three years?",
  "Think about something you consider a failure in your life, and tell me why you think it happened.",
  "How do you think you will fit into this operation?",
  "If you were hired, what ideas/talents could you contribute to the position or our company?",
  "Give an example where you showed leadership and initiative.",
  "Give an example of when you were able to contribute to a team project.",
  "What have you done to develop or change in the last few years?",
  "Do you have any questions for me?",
];

const ask = [
  "How well is the position defined?",
  "Please describe an average day on this job.",
  "What aspects of this job would you like to see performed better?",
  "What are the key challenges or problems of this position?",
  "How would you describe the ideal candidate?",
  "When and how will I be evaluated?",
  "What are the performance standards?",
  "With whom would I be working?",
  "What is the department's environment like?",
  "When will you make the hiring decision?",
  "May I call you for the decision?",
];

const datas = {
  code: code,
  word: word,
  personal: personal,
  ask: ask,
};
